### ISSUE TITLE
Murder Mystery (PWP)

### ISSUE THREAD

**Issue by asadmehdi785** [ExplorerAdventure/pwp-capstones#1]
### Criteria 1: Valid Python Code
* _Score Level:_ 4
* _Comment(s):_ Code included runs without any errors.
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4
* _Comment(s):_ Code produces the suite of functions and classes required of it and calls them in an appropriate order.
 
### Criteria 3: Software Architecture
* _Score Level:_ 4
* _Comment(s):_ Code is separated into distinct classes and functions each which are invoked for their own purposes.
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 4
* _Comment(s):_ Code uses language features appropriately. If a task can be solved with a Python language feature, it is.

### Criteria 5: Produces Accurate Output
* _Score Level:_ 2
* _Comment(s):_ Code output is properly formatted and accurate, but overall answer is incorrect!
 
### Overall Score: 18/20
Overall, excellent work with this project. You did a good job going through the project requirements and implementing them using appropriate Python language features. You also did a good job separating your code into different classes and methods in order to implement the requirements.

However, althought you got the correct similarity scores at the end, you accidentally picked the wrong individual! Recall that these were the similarity scores:

```
Lily's note has a similarity score of 0.770830594519 to the murder note
Myrtle's note has a similarity score of 0.317870016555 to the murder note
Gregg's note has a similarity score of 0.698804363524 to the murder note
```

With this, we should pick Lily as the culprit. However, in the file you uploaded it looks like you picked Gregg. Besides for that though you did a good job with this project!

I hope you enjoyed the course!

**Comment by ExplorerAdventure** [comment]
Thanks for the review, I loved the course and found it challenging enough. Plan to do another one in 2 months time.
